FROM python:latest

COPY app.py /app/
COPY documents.sql /app/
COPY key.txt /app/

WORKDIR /app

RUN pip install flask
RUN pip install requests

ENV FLASK_APP=app.py


CMD ["flask", "--debug","run", "--host=0.0.0.0", "--port=5001"]

