DROP TABLE IF EXISTS logs;
CREATE TABLE IF NOT EXISTS logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event TEXT,
    user TEXT,
    filename TEXT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);